name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Pact provider verification
    runs-on: ubuntu-18.04

    steps:
      - name: Get providers needing verfication
        id: get-providers
        uses: stephencdaly/get-pact-providers-needing-validation
        with:
          pact-broker-url: ${{ secrets.PactBrokerUrl }}
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: c494049e499de04a12b0d4d0b84c5d961b6ec5e2
      - name: Output provider list
        run: echo "Provider list ${{ steps.get-providers.outputs.providers-needing-validation }}"