name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Pact provider verification
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get providers needing verfication
        id: get-providers
        uses: stephencdaly/pay-actions/get-pact-providers-needing-validation@main
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: de7889a74feb8a595da7695de82e00b31ec0b564
      - name: Output provider list
        run: echo "Provider list ${{ steps.get-providers.outputs.providers-needing-validation }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-ledger-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-ledger-m2
      - name: Checkout ledger master
        uses: actions/checkout@v2
        with:
          repository: alphagov/pay-ledger
          path: ledger
      - name: Run pact provider tests
        uses: stephencdaly/pay-actions/pact-provider-tests@main
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: de7889a74feb8a595da7695de82e00b31ec0b564
          provider: ledger
